import Head from "next/head";
import React, { useState, useEffect } from "react";
import axios from "axios";
import FrontLayout from "@/components/Layout";
import Summary from "@/components/Summary";

export default function Home() {
  const [active, setActive] = useState("summary");
  const [counts, setCounts] = useState([]);

  useEffect(() => {
    try {
      axios.get("/count").then((res) => {
        console.log(res.data.data);
        setCounts(res.data.data);
      });
    } catch (err) {
      console.log(err);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontLayout>
        <div className="mx-40 pt-6">
          <div className="flex w-1/2 mx-auto justify-between">
            <div
              onClick={() => setActive("summary")}
              className={
                active === "summary"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Summary
            </div>
            <div
              onClick={() => setActive("content")}
              className={
                active === "content"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Manage Content
            </div>
            <div
              onClick={() => setActive("user")}
              className={
                active === "user"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              User
            </div>
            <div
              onClick={() => setActive("report")}
              className={
                active === "report"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Report
            </div>
          </div>
          <div className="pt-4">
            {(() => {
              switch (active) {
                case "summary":
                  return <Summary summary={counts} />;
                case "content":
                  return <div>Hello content</div>;
                case "user":
                  return <div>Hello user</div>;
                case "report":
                  return <div>Hello report</div>;
              }
            })()}
          </div>
        </div>
      </FrontLayout>
    </>
  );
}
