import Head from "next/head";
import React, { useState, useEffect } from "react";
import axios from "axios";
import FrontLayout from "@/components/Layout";

export default function Home() {
  const [active, setActive] = useState("summary");
  const [counts, setCounts] = useState([]);

  useEffect(() => {
    // axios
    //   .get("https://shark-app-28vbj.ondigitalocean.app/v1/admin/count")
    //   .then((res) => {
    //     setCounts(res.data);
    //     console.log(res.data);
    //   });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontLayout className="py-10">
        <div className="mx-40 mt-4">
          <div className="flex w-1/2 mx-auto justify-between">
            <div
              onClick={() => setActive("summary")}
              className={
                active === "summary"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Summary
            </div>
            <div
              onClick={() => setActive("content")}
              className={
                active === "content"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Manage Content
            </div>
            <div
              onClick={() => setActive("user")}
              className={
                active === "user"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              User
            </div>
            <div
              onClick={() => setActive("report")}
              className={
                active === "report"
                  ? "border-b border-warning cursor-pointer"
                  : "cursor-pointer"
              }
            >
              Report
            </div>
          </div>
          <div>
            {(() => {
              switch (active) {
                case "summary":
                  return <div>Hello</div>;
                case "content":
                  return <div>Hello content</div>;
                case "user":
                  return <div>Hello user</div>;
                case "report":
                  return <div>Hello report</div>;
              }
            })()}
          </div>
        </div>
      </FrontLayout>
    </>
  );
}
